#!/bin/sh

PROG=/usr/bin/bootstrap-server
PID_FILE=/var/run/bootstrap-server.pid

start_server(){
    DISPLAY_ROTATE=0
    board=$(/usr/bin/get_sn_mac.sh board)
    if [ "$board" != "NEBULA V1.0.0.1" ]; then
      DISPLAY_ROTATE=3
      # seems like the k1 board might need a bit longer
      sleep 30
    fi

    # kill the boot display so it does not keep showing over top of grumpyscreen
    killall boot_display 2> /dev/null
    # display black transition image to stop the corrupt image being shown
    cmd_jpeg_display /etc/logo/black.jpg &

    sync && echo 3 > /proc/sys/vm/drop_caches

    DISPLAY_ROTATE=$DISPLAY_ROTATE start-stop-daemon -S -q -b -m -p $PID_FILE --exec $PROG
}

stop_server() {
  local service_pid="$(cat $PID_FILE 2> /dev/null)"
  local is_running=false
  if [ -n "$service_pid" ] && [ -d /proc/"$service_pid" ]; then
    is_running=true
  fi

  start-stop-daemon -K -q -p $PID_FILE > /dev/null 2>&1

  if [ "$is_running" = "true" ]; then
      # after stopping bootstrap, clear the screen with this afterwards to avoid showing a corrupted image
      cmd_jpeg_display /etc/logo/black.jpg
  fi
}

case "$1" in
    start)
        start_server
        ;;
    stop)
        stop_server
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage:"
        echo "    $0 {start|stop|restart}"
        exit 1
esac

exit $?
